// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type MessageResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SaveMessageRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMessageRequest) Reset()         { *m = SaveMessageRequest{} }
func (m *SaveMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SaveMessageRequest) ProtoMessage()    {}
func (*SaveMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *SaveMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMessageRequest.Unmarshal(m, b)
}
func (m *SaveMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMessageRequest.Marshal(b, m, deterministic)
}
func (m *SaveMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMessageRequest.Merge(m, src)
}
func (m *SaveMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SaveMessageRequest.Size(m)
}
func (m *SaveMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMessageRequest proto.InternalMessageInfo

func (m *SaveMessageRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SaveMessageRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SaveMessageResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMessageResponse) Reset()         { *m = SaveMessageResponse{} }
func (m *SaveMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SaveMessageResponse) ProtoMessage()    {}
func (*SaveMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *SaveMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMessageResponse.Unmarshal(m, b)
}
func (m *SaveMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMessageResponse.Marshal(b, m, deterministic)
}
func (m *SaveMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMessageResponse.Merge(m, src)
}
func (m *SaveMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SaveMessageResponse.Size(m)
}
func (m *SaveMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMessageResponse proto.InternalMessageInfo

func (m *SaveMessageResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "messages.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "messages.MessageResponse")
	proto.RegisterType((*SaveMessageRequest)(nil), "messages.SaveMessageRequest")
	proto.RegisterType((*SaveMessageResponse)(nil), "messages.SaveMessageResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x94,
	0xb8, 0xf8, 0x7c, 0x21, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6,
	0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x49, 0x9d, 0x8b, 0x1f,
	0xae, 0xa6, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34,
	0x15, 0xaa, 0x0c, 0xc2, 0x51, 0xb2, 0xe1, 0x12, 0x0a, 0x4e, 0x2c, 0x4b, 0x25, 0x64, 0x20, 0x42,
	0x37, 0x13, 0xb2, 0x6e, 0x55, 0x2e, 0x61, 0x14, 0xdd, 0x50, 0xab, 0xf8, 0xb8, 0x98, 0xf2, 0xb3,
	0xc1, 0xba, 0x39, 0x82, 0x98, 0xf2, 0xb3, 0x8d, 0x16, 0x33, 0xc2, 0x9d, 0x1c, 0x9c, 0x5a, 0x54,
	0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xcc, 0xc5, 0xe5, 0x9e, 0x5a, 0x02, 0x15, 0x14, 0x92, 0xd0, 0x83,
	0xfb, 0x16, 0xd5, 0x25, 0x52, 0x92, 0x58, 0x64, 0x20, 0xb6, 0x28, 0x31, 0x08, 0xf9, 0x70, 0x71,
	0x23, 0x59, 0x2f, 0x24, 0x83, 0x50, 0x8b, 0xe9, 0x27, 0x29, 0x59, 0x1c, 0xb2, 0x30, 0xd3, 0x9c,
	0xec, 0xb9, 0xd4, 0x92, 0xf3, 0x73, 0xf5, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x0a, 0x12,
	0x4b, 0x8a, 0x32, 0x93, 0xb3, 0x8b, 0xf2, 0x53, 0x52, 0x53, 0xe1, 0x3a, 0x21, 0x8e, 0x77, 0x12,
	0x46, 0xf5, 0x4c, 0x00, 0x28, 0x82, 0x02, 0x18, 0x93, 0xd8, 0xc0, 0x31, 0x65, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x5e, 0x40, 0x5c, 0xd1, 0xbb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	GetMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	SaveMessage(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) GetMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/messages.MessageService/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SaveMessage(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error) {
	out := new(SaveMessageResponse)
	err := c.cc.Invoke(ctx, "/messages.MessageService/SaveMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	GetMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	SaveMessage(context.Context, *SaveMessageRequest) (*SaveMessageResponse, error)
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.MessageService/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SaveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SaveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.MessageService/SaveMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SaveMessage(ctx, req.(*SaveMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessage",
			Handler:    _MessageService_GetMessage_Handler,
		},
		{
			MethodName: "SaveMessage",
			Handler:    _MessageService_SaveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
